# Sklearn

## sklearn.model_selection

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn import model_selection, datasets

import numpy as np

/root/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [36]:
iris = datasets.load_iris()

In [37]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [38]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [39]:
print('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data)))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [40]:
print('Обучающая выборка:\n', train_data[:5])
print('\n')
print('Тестовая выборка:\n', test_data[:5])

Обучающая выборка:
 [[5.5 2.4 3.8 1.1]
 [4.8 3.  1.4 0.1]
 [6.1 3.  4.6 1.4]
 [6.3 2.5 5.  1.9]
 [5.3 3.7 1.5 0.2]]


Тестовая выборка:
 [[6.4 3.1 5.5 1.8]
 [7.7 2.8 6.7 2. ]
 [6.3 3.3 6.  2.5]
 [5.8 2.8 5.1 2.4]
 [5.4 3.9 1.7 0.4]]


In [41]:
print('Метки классов на обучающей выборке:\n', train_labels)
print('\n')
print('Метки классов на тестовой выборке:\n', test_labels)

Метки классов на обучающей выборке:
 [1 0 1 2 0 1 1 0 2 0 1 0 2 1 0 1 2 0 0 0 1 0 1 2 1 1 1 2 2 2 0 1 0 2 0 1 0
 1 2 2 2 0 0 1 2 2 0 1 1 2 0 2 1 2 2 2 2 1 1 0 0 1 0 0 2 2 1 2 1 2 0 2 0 0
 1 1 2 1 2 1 0 2 1 0 1 0 2 1 2 1 1 0 0 2 2 0 1 2 1 2 1 0 1 0 2]


Метки классов на тестовой выборке:
 [2 2 2 2 0 1 1 0 0 1 2 1 0 0 2 0 1 1 0 0 0 0 1 2 0 0 1 1 2 0 2 2 1 2 2 1 1
 0 0 2 2 2 0 1 0]


### Стратегии проведения кросс-валидации

In [42]:
#сгенерируем короткое подобие датасета, где элементы совпадают с порядковым номером
X = range(0,10)

#### KFold

In [43]:
kf = model_selection.KFold(n_splits = 5)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [44]:
kf = model_selection.KFold(n_splits = 2, shuffle = True)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[1 2 3 7 9] [0 4 5 6 8]
[0 4 5 6 8] [1 2 3 7 9]


In [45]:
kf = model_selection.KFold(n_splits = 2, shuffle = True, random_state = 1)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [46]:
y = np.array([0] * 5 + [1] * 5)
print(y)

skf = model_selection.StratifiedKFold(n_splits = 2, shuffle = True, random_state = 0)
for train_indices, test_indices in skf.split(X, y):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [47]:
target = np.array([0, 1] * 5)
print(target)

skf = model_selection.StratifiedKFold(n_splits = 2,shuffle = True)
for train_indices, test_indices in skf.split(X, target):
    print(train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]
[2 3 6 7] [0 1 4 5 8 9]
[0 1 4 5 8 9] [2 3 6 7]


#### ShuffleSplit

In [48]:
ss = model_selection.ShuffleSplit(n_splits = 10, test_size = 0.2)

for train_indices, test_indices in ss.split(X):
    print(train_indices, test_indices)

[2 9 5 3 0 8 7 4] [6 1]
[8 9 7 4 3 2 0 5] [1 6]
[9 4 1 3 7 8 2 6] [0 5]
[3 9 2 7 1 8 0 6] [4 5]
[9 8 6 2 4 3 7 0] [5 1]
[7 1 2 4 9 8 6 0] [3 5]
[3 7 4 6 1 5 0 2] [9 8]
[7 6 1 8 5 0 9 4] [2 3]
[1 2 9 6 5 7 0 3] [4 8]
[5 2 7 3 6 0 9 4] [1 8]


#### StratifiedShuffleSplit

In [49]:
target = np.array([0] * 5 + [1] * 5)
print(target)

sss = model_selection.StratifiedShuffleSplit(n_splits = 4, test_size = 0.2)
for train_indices, test_indices in sss.split(X, target):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[9 4 2 5 0 3 8 7] [6 1]
[1 2 4 5 8 9 3 7] [6 0]
[9 5 3 8 2 1 4 6] [0 7]
[1 2 4 6 3 5 8 9] [0 7]


#### Leave-One-Out

In [50]:
loo = model_selection.LeaveOneOut()

for train_indices, test_index in loo.split(X):
    print(train_indices, test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators